name: A workflow that is gonna be called from outside repo
on:
  workflow_call:

    inputs:
      input1:
        type: string
        required: true

    outputs:
      secret_called_repo:
      description: "This is a secret in the repo of a called workflow"
      value: ${{ jobs.job1.outputs.secret_called_repo }}
jobs:

  job1:
    runs-on: ubuntu-latest
    outputs:
      secret_called_repo: ${{ steps.step1.outputs.secret_called_repo }}
    steps:

      - name: step1
        id: step1
        run: |
         echo "This is a step 1 from called workflow"
         echo "This is a secret from the repo where called_workflow resides: ${{ secrets.called_workflow }}"
         echo "secret_called_repo=${{secrets.called_workflow }} >> $GITHUB_OUTPUT"
         echo "This is passed from caller workflow as a input: ${{ inputs.input1 }}"
         echo "This is a secret inherited from the calling workflow: ${{ secrets.caller_workflow }}"
